name: Build App

on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: eslint
        run: npx eslint

      - name: test (jest)
        run: npm test

      - name: Build app (if applicable)
        run: npm run build
